export const MOCK = {
  company: {
    name: "Acme Holdings",
    qbConnected: true,
    lastSync: "12 minutes ago",
  },
  stats: {
    revenueMTD: 184320,
    revenuePrev: 162840,
    cashOnHand: 412900,
    burnRate: 38500,
    runwayMonths: 10.7,
    arDays: 32,
    grossMargin: 0.62,
    netMargin: 0.18,
  },
  revenueByMonth: [
    { m: "Dec", v: 142_000 },
    { m: "Jan", v: 156_000 },
    { m: "Feb", v: 149_500 },
    { m: "Mar", v: 168_200 },
    { m: "Apr", v: 162_840 },
    { m: "May", v: 184_320 },
  ],
  cashFlow: [
    { d: "Today", balance: 412_900 },
    { d: "+30d",  balance: 388_200 },
    { d: "+60d",  balance: 351_400 },
    { d: "+90d",  balance: 328_600 },
  ],
  topRevenue: [
    { name: "Customer A", value: 48200, pct: 26 },
    { name: "Customer B", value: 32450, pct: 18 },
    { name: "Customer C", value: 24800, pct: 13 },
    { name: "Customer D", value: 19600, pct: 11 },
    { name: "Other (12)", value: 59270, pct: 32 },
  ],
  expensesByCategory: [
    { c: "Payroll",    v: 22_400, pct: 58 },
    { c: "Software",   v: 4_800,  pct: 12 },
    { c: "Marketing",  v: 4_200,  pct: 11 },
    { c: "Operations", v: 3_900,  pct: 10 },
    { c: "Travel",     v: 1_600,  pct: 4  },
    { c: "Other",      v: 1_600,  pct: 5  },
  ],
  risks: [
    { kind: "warn", title: "3 invoices overdue 30+ days",          body: "Customer C, F, and J owe a combined $XX,XXX past 30 days. Average DSO climbing.",           tag: "AR Risk" },
    { kind: "neg",  title: "Software spend up 41% vs. last quarter", body: "$X,XXX increase concentrated in Q2. Largest jump: SaaS subscriptions.",                   tag: "Expense" },
    { kind: "warn", title: "Runway will dip below 9 months by August", body: "At current burn ($XX,XXX/mo), cash reserves cross threshold ~Aug 14.",                  tag: "Cash"    },
    { kind: "pos",  title: "Gross margin improved 3.2 pts",         body: "COGS down vs. revenue growth. Sustained over 3 months.",                                   tag: "Margin"  },
  ],
  invoices: [
    { id: "INV-1042", customer: "Customer A", issued: "May 18, 2026", due: "Jun 17, 2026", amount: 12_400, status: "Unpaid"  },
    { id: "INV-1041", customer: "Customer B", issued: "May 14, 2026", due: "Jun 13, 2026", amount: 8_950,  status: "Unpaid"  },
    { id: "INV-1040", customer: "Customer C", issued: "Apr 12, 2026", due: "May 12, 2026", amount: 6_200,  status: "Overdue" },
    { id: "INV-1039", customer: "Customer A", issued: "Apr 02, 2026", due: "May 02, 2026", amount: 11_300, status: "Paid"    },
    { id: "INV-1038", customer: "Customer D", issued: "Mar 28, 2026", due: "Apr 27, 2026", amount: 4_750,  status: "Paid"    },
    { id: "INV-1037", customer: "Customer B", issued: "Mar 14, 2026", due: "Apr 13, 2026", amount: 9_100,  status: "Paid"    },
    { id: "INV-1036", customer: "Customer E", issued: "Mar 02, 2026", due: "Apr 01, 2026", amount: 3_400,  status: "Paid"    },
  ],
  customerInvoices: [
    { id: "INV-1042", issued: "May 18, 2026", due: "Jun 17, 2026", amount: 12_400, status: "Unpaid" },
    { id: "INV-1039", issued: "Apr 02, 2026", due: "May 02, 2026", amount: 11_300, status: "Paid"   },
    { id: "INV-1031", issued: "Mar 02, 2026", due: "Apr 01, 2026", amount: 9_800,  status: "Paid"   },
    { id: "INV-1024", issued: "Feb 02, 2026", due: "Mar 04, 2026", amount: 10_400, status: "Paid"   },
    { id: "INV-1018", issued: "Jan 02, 2026", due: "Feb 01, 2026", amount: 8_900,  status: "Paid"   },
  ],
  companies: [
    { id: 1, name: "Acme Holdings",      customers: 14, qb: "Connected",     plan: "Pro",     active: true,  lastActive: "2 min ago"   },
    { id: 2, name: "Northwind Studios",  customers: 32, qb: "Connected",     plan: "Pro",     active: true,  lastActive: "1 hour ago"  },
    { id: 3, name: "Belford & Co.",      customers: 6,  qb: "Reauth needed", plan: "Starter", active: true,  lastActive: "5 hours ago" },
    { id: 4, name: "Linnaeus Capital",   customers: 21, qb: "Connected",     plan: "Pro",     active: true,  lastActive: "yesterday"   },
    { id: 5, name: "Pacific Roastery",   customers: 9,  qb: "Disconnected",  plan: "Starter", active: false, lastActive: "3 days ago"  },
    { id: 6, name: "Halcyon Print Works",customers: 17, qb: "Connected",     plan: "Pro",     active: true,  lastActive: "12 min ago"  },
    { id: 7, name: "Marais Architects",  customers: 4,  qb: "Connected",     plan: "Starter", active: true,  lastActive: "3 hours ago" },
  ],
  aiLogs: [
    { t: "11:42 AM", company: "Acme Holdings",       role: "Company",  query: "Forecast cash flow for next 90 days",    ms: 2840 },
    { t: "11:38 AM", company: "Northwind Studios",   role: "Company",  query: "Why did expenses spike in March?",       ms: 3120 },
    { t: "11:30 AM", company: "Acme Holdings",       role: "Customer", query: "What do I owe this month?",              ms: 1410 },
    { t: "11:22 AM", company: "Linnaeus Capital",    role: "Company",  query: "Top 5 customers by revenue YTD",         ms: 2210 },
    { t: "11:14 AM", company: "Halcyon Print Works", role: "Company",  query: "Which invoices are 30+ days overdue?",   ms: 1980 },
    { t: "10:58 AM", company: "Belford & Co.",       role: "Customer", query: "When is my next invoice due?",           ms: 920  },
    { t: "10:44 AM", company: "Marais Architects",   role: "Company",  query: "Gross margin trend this year",           ms: 2540 },
  ],
};
